// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien.Data;

#nullable disable

namespace QuanLyThuVien.Migrations
{
    [DbContext(typeof(ThuVienContext))]
    [Migration("20251124174426_UpdateSudocSchema")]
    partial class UpdateSudocSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("QuanLyThuVien.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .HasColumnType("TEXT");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhBia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoSan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhaXuatBan")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoHieu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TacGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomTat")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSach");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.Sach", b =>
                {
                    b.HasOne("QuanLyThuVien.Models.TheLoai", "TheLoai")
                        .WithMany("Sachs")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien.Models.TheLoai", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
